<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Shapes.fsi" />
    <Compile Include="Shapes.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
